name: soulscribe
description: "A journal app to capture your thoughts and track your mood daily."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  share_plus: ^10.0.2

  # Packages for managing states and user data
  get: ^4.6.6
  shared_preferences: ^2.3.2

  # Essential UI components
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.7.0
  iconly: ^1.0.1

  # UI widgets
  flutter_spinkit: ^5.2.1
  typewritertext: ^3.0.9

  # RoundedLoadingButton requrement
  rxdart: ^0.28.0

  # UnDraw requrements
  fhir_yaml: ^0.9.0
  cli_util: ^0.4.1
  yaml: ^3.1.2
  flutter_svg: ^2.0.9

  # TableCalendar requrements
  simple_gesture_detector: ^0.2.1
  intl: ^0.19.0
  
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.jpg
    - assets/images/analyze.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/mood/